### ISSUE TITLE
Form validation for add a job form

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Job-Portal#8]

**Comment by CA-MKSingh** [comment]
Hey @Karan2310 , I would like to work on this, can you please provide some detail?

**Comment by Karan2310** [comment]
The form takes the empty string as valid input so need to add a check with javascript (basic form validation)

**Comment by CA-MKSingh** [comment]
can you please assign this to me?

**Comment by CA-MKSingh** [comment]
thanks for assigning @Karan2310 
I have started working

**Comment by CA-MKSingh** [comment]
Hi @Karan2310, I've created the PR. Please have a look and let me know if any change is required.

![image](https://user-images.githubusercontent.com/52215756/197395894-336b5364-81bc-47e9-9bb6-091f15ad418b.png)

**Comment by CA-MKSingh** [comment]
Hey @Karan2310 , any update?

**Comment by CA-MKSingh** [comment]
Hey @ayusshh19 , can you please have a look on it regarding merging
